### ISSUE TITLE
Issue with parsing GPX

### ISSUE THREAD

**Issue by jperrine088** [yasoob/nrc-exporter#10]
Hello - I was able to download the JSON files by using your older BASH script. I came across the nrc-exporter after downloading all of my data and chose to use the nrc-exporter -I command to parse the JSON files to GPX. I even ran under the sudo command and added -v for the detailed output. Is there something wrong with my data or are the dependencies jacked up? Appreciate your help.

```
pi@raspberrypi:~/Documents $ sudo nrc-exporter -i activities -v

  _   _ ____   ____                              _            
 | \ | |  _ \ / ___|   _____  ___ __   ___  _ __| |_ ___ _ __ 
 |  \| | |_) | |      / _ \ \/ / '_ \ / _ \| '__| __/ _ \ '__|
 | |\  |  _ <| |___  |  __/>  <| |_) | (_) | |  | ||  __/ |   
 |_| \_|_| \_\____|  \___/_/\_\ .__/ \___/|_|   \__\___|_|   
                               |_|                            

                                            ~ Yasoob Khalid
                                              https://yasoob.me


[-] 🐛 Passed in arguments:
[-] 🐛           Email: None
[-] 🐛           Password: None
[-] 🐛           Token: None
[+] Starting NRC Exporter
[+] Parsing activity JSON files from the activities folders
[-] 🐛 Parsing activity: dict_keys(['id', 'type', 'app_id', 'start_epoch_ms', 'end_epoch_ms', 'last_modified', 'active_duration_ms', 'session', 'delete_indicator', 'summaries', 'sources', 'tags', 'change_tokens', 'metric_types', 'metrics', 'moments'])
[-] 🐛   Activity 938822d0-f084-4218-9e91-7d098b389922 contains the following metrics: ['elevation', 'descent', 'ascent', 'distance', 'latitude', 'pace', 'heart_rate', 'calories', 'speed', 'nikefuel', 'longitude']
[+] ✔ Activity 938822d0-f084-4218-9e91-7d098b389922 successfully parsed
[-] 🐛 Parsing activity: dict_keys(['id', 'type', 'app_id', 'start_epoch_ms', 'end_epoch_ms', 'last_modified', 'active_duration_ms', 'session', 'delete_indicator', 'summaries', 'sources', 'tags', 'change_tokens', 'metric_types', 'metrics', 'moments'])
[-] 🐛   Activity 75912ad2-6cef-41ad-bf6e-41c1e9a6fe74 contains the following metrics: ['elevation', 'distance', 'rpe', 'latitude', 'pace', 'heart_rate', 'calories', 'speed', 'nikefuel', 'descent', 'ascent', 'longitude']
[+] ✔ Activity 75912ad2-6cef-41ad-bf6e-41c1e9a6fe74 successfully parsed
[-] 🐛 Parsing activity: dict_keys(['error_id', 'errors'])
Traceback (most recent call last):
  File "/usr/local/bin/nrc-exporter", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/nrc_exporter.py", line 631, in main
    parsed_data = parse_activity_data(json_data)
  File "/usr/local/lib/python3.7/dist-packages/nrc_exporter.py", line 449, in parse_activity_data
    for i, metric in enumerate(activity["metrics"]):
KeyError: 'metrics'
```

**Comment by yihong0618** [comment]
May be in miles? we sould test this and change the gpx format also。

**Comment by yihong0618** [comment]
@jperrine088 can you open the error json file and see the line caused this error about the unit?

**Comment by yasoob** [comment]
There is something wrong with your activity file. It contains the `error_id` and `errors` keys. An actual activity file contains other keys. Like @yihong0618 said, can you please share the activity file that caused this error? In it's current state `nrc-exporter` doesn't print the name of the file that caused this error. If you can't manually find the problematic activity file I can modify the code to output the filename.

**Comment by jperrine088** [comment]
I have over 500 activities I think it would be a good idea to add the file
name output.

**Comment by yasoob** [comment]
@jperrine088 I have updated the code in the GitHub repo. Please install from here. Now it should also print the name of the file being processed.

**Comment by jperrine088** [comment]
Still not working...

[+] Starting NRC Exporter
[+] Parsing activity JSON files from the activities folders
[-] 🐛 Parsing file: activities/c9de2005-1165-4d5d-976a-3052856ef654.json
[-] 🐛 Parsing activity: dict_keys(['id', 'type', 'app_id', 'start_epoch_ms', 'end_epoch_ms', 'last_modified', 'active_duration_ms', 'session', 'delete_indicator', 'summaries', 'sources', 'tags', 'change_tokens', 'metric_types', 'moments'])
Traceback (most recent call last):
  File "./nrc_exporter.py", line 646, in <module>
    main()
  File "./nrc_exporter.py", line 632, in main
    parsed_data = parse_activity_data(json_data)
  File "./nrc_exporter.py", line 449, in parse_activity_data
    for i, metric in enumerate(activity["metrics"]):

**Comment by yihong0618** [comment]
@yasoob 
Locate this bug,  some nike file will look like this (wear os or something)
I think we can handle the error and continue?
I can take a pr.
![image](https://user-images.githubusercontent.com/15976103/95216052-3b336180-0824-11eb-8691-7a981a7cabfc.png)

**Comment by yasoob** [comment]
@yihong0618 that sounds good! If you don't mind I would love to add you as a collaborator to the project as I have less time on my hand these days and you can continue working on it with greater degree of control. Is that something you would be interested in?

**Comment by yihong0618** [comment]
@yasoob of course I lave interest. Its my pleasure, thank you~

**Comment by yasoob** [comment]
@yihong0618 best. Just sent you the invite  :)

**Comment by yihong0618** [comment]
> @yihong0618 best. Just sent you the invite  :)

Accept~.

**Comment by yihong0618** [comment]
@jperrine088  fixed, can you check?  Please check with `git clone` way, its not upload to pypi yet.
